// Constants for Action calls
export const UPDATE_ALERT_SNACK_SUCCESS = 'UPDATE_ALERT_SNACK_SUCCESS';
export const UPDATE_PREDICTION = 'UPDATE_PREDICTION';
export const UPDATE_ITERATION = 'UPDATE_ITERATION';
export const TOGGLE_TRAINING = 'TOGGLE_TRAINING';
export const STOP_TRAINING = 'STOP_TRAINING';
export const RESET_MODEL = 'RESET_MODEL';
export const FIRST_CALL = 'FIRST_CALL';